module.exports = {
  eventos: {
    brics: [
      "2001: Termo BRIC cunhado por Jim O'Neill - O conceito de BRIC (Brasil, Rússia, Índia, China) é introduzido como um grupo de economias emergentes.",
      "2006: Primeira cúpula do BRICS - Os países BRIC se reúnem oficialmente pela primeira vez para discutir cooperação econômica, política e segurança.",
      "2010: Expansão para BRICS - África do Sul se junta ao BRIC, formando o BRICS, abrangendo agora cinco países com forte crescimento econômico.",
      "2014: Criação do Novo Banco de Desenvolvimento (NBD) - O BRICS cria o NBD, com o objetivo de financiar projetos de infraestrutura e desenvolvimento nos países em desenvolvimento.",
      "2015: Acordo do BRICS com a criação do Contingent Reserve Arrangement (CRA) - Um mecanismo financeiro para prevenir crises cambiais, com um fundo de US$ 100 bilhões.",
      "2021: Expansão do BRICS+ - Discussões iniciadas sobre a ampliação do BRICS para incluir mais países com economias emergentes como Argentina, Irã e outros.",
      "2024: Expansão formal do BRICS+ - Inclusão de novos membros, ampliando o bloco para uma influência política e econômica ainda maior.",
      "2023: Cúpula BRICS em Joanesburgo - O BRICS reafirma seu papel central na política internacional, destacando a oposição ao hegemonismo ocidental e fortalecendo as trocas comerciais intra-bloco.",
      "2023: Adoção de novas estratégias para a independência monetária - Discussões sobre a criação de uma moeda comum para o BRICS, visando reduzir a dependência do dólar nas transações internacionais.",
      "2024: BRICS e a Nova Ordem Global - Discussões sobre a reforma das instituições financeiras globais, como o FMI e o Banco Mundial, com o BRICS buscando maior participação em decisões econômicas globais."
    ],
    mercosul: [
      "1991: Tratado de Assunção - Criação do Mercosul (Mercado Comum do Sul) por Brasil, Argentina, Paraguai e Uruguai, com o objetivo de promover a integração econômica e política.",
      "1994: Protocolo de Ouro Preto - Estabelecimento das estruturas institucionais do Mercosul, incluindo o Parlamento do Mercosul (Parlasul) e o Comitê de Representantes Permanentes.",
      "2005: Entrada da Venezuela no Mercosul - A Venezuela se torna membro pleno do Mercosul, ampliando o bloco com uma economia petrolífera.",
      "2012: Suspensão do Paraguai do Mercosul - Após o impeachment de Fernando Lugo, o Paraguai é suspenso do bloco por violação de normas democráticas.",
      "2016: Acordo Mercosul-União Europeia - Acordo político e comercial é firmado após 20 anos de negociações, criando uma das maiores zonas de livre comércio do mundo.",
      "2020: Acordo Mercosul-China - Negociação de um acordo de livre comércio entre o Mercosul e a China, com foco em ampliar as trocas comerciais e a cooperação em tecnologia.",
      "2021: Retorno da presidência do Mercosul ao Brasil - O Brasil assume a presidência rotativa do Mercosul, com foco em estimular a economia regional e reduzir barreiras comerciais.",
      "2022: Acordo Mercosul-ASEAN - O Mercosul inicia negociações para um acordo de livre comércio com os países da Associação de Nações do Sudeste Asiático (ASEAN), visando ampliar os mercados.",
      "2023: Desafios e renovação do Mercosul - Discussões sobre a reformulação interna do Mercosul, incluindo novos acordos comerciais com outras potências globais como os EUA e a Índia.",
      "2024: Acordo Mercosul-Índia - Discussões sobre um novo acordo de comércio livre com a Índia, visando aumentar a troca de produtos agrícolas, tecnologia e investimentos."
    ],
    integracao_sulamericana: [
      "2008: Criação da Unasul - A União das Nações Sul-Americanas é criada com o objetivo de promover a integração política e econômica dos países da América do Sul.",
      "2010: Início do Fórum de Parcerias de Cooperação Econômica América Latina-Ásia (ALADI) - Fortalecimento das relações entre a América Latina e os países asiáticos, ampliando o comércio internacional.",
      "2018: Crise política no Mercosul - Dificuldades econômicas e políticas no Mercosul devido a divergências internas, como a saída da Venezuela e o fracasso em avançar com acordos comerciais globais.",
      "2021: Criação do CELAC (Comunidade de Estados Latino-Americanos e Caribenhos) - A CELAC visa consolidar a união regional, mas enfrenta desafios devido às divergências políticas entre seus membros.",
      "2023: Novas iniciativas para integração econômica regional - Iniciativas para fortalecer o Mercosul com novos acordos, incluindo o uso de criptomoedas como parte das soluções financeiras para promover o comércio.",
      "2024: Novos desafios para a Unasul - A crise política e econômica afeta a integração regional, com países buscando alternativas para fortalecer a cooperação sul-americana sem depender de blocos como a OMC.",
      "2024: Discussões sobre um novo modelo de integração - A América do Sul começa a discutir novos modelos de integração, com foco em novos mercados e alianças fora das esferas tradicionais de influência, como a OMC e a União Europeia."
    ],
    economia_politica_global: [
      "1944: Conferência de Bretton Woods - Criação do sistema financeiro internacional pós-Segunda Guerra Mundial, incluindo o FMI e o Banco Mundial",
      "1971: Fim do padrão ouro - Os EUA abandonam o padrão ouro, levando a uma mudança para moedas fiduciárias como padrão global",
      "1980s: Neoliberalismo global - Políticas econômicas de mercado livre ganham força, especialmente com Ronald Reagan (EUA) e Margaret Thatcher (Reino Unido)",
      "1994: Acordo de Livre Comércio da América do Norte (NAFTA) - Acordo trilateral entre EUA, México e Canadá para eliminar barreiras comerciais",
      "1997-1998: Crise financeira asiática - Colapso de várias economias do sudeste asiático devido a políticas cambiais e especulação financeira",
      "2007-2008: Crise financeira global - Colapso do sistema financeiro mundial, levando a uma recessão global e a um aumento da regulação financeira",
      "2011: Crise da dívida soberana na zona do euro - Economias como Grécia, Portugal e Espanha enfrentam sérios problemas fiscais, afetando a economia global",
      "2020: Pandemia de COVID-19 - Colapso de cadeias produtivas globais e recessão econômica mundial, seguida por pacotes de estímulo fiscal sem precedentes",
    ],
    politica_internacional: [
      "1917: Revolução Russa - Fundação do Partido Comunista da União Soviética (PCUS) e início da construção do socialismo soviético 🇷🇺",
      "1921: Fundação do Partido Comunista Chinês - Início do movimento comunista que levaria à criação da República Popular da China 🇨🇳",
      "1945: Criação da ONU - Após a Segunda Guerra Mundial, criação da Organização das Nações Unidas com objetivo de manter a paz e segurança internacional",
      "1949: Revolução Chinesa - Mao Zedong funda a República Popular da China 🇨🇳",
      "1959: Revolução Cubana - Fidel Castro e Che Guevara derrubam o regime de Fulgencio Batista. Impacto na América Latina e na Guerra Fria 🇨🇺",
      "1960-70: Guerrilhas de esquerda na América Latina - Foco em movimentos de guerrilhas em países como Brasil, Argentina e El Salvador",
      "1979: Revolução Iraniana - Queda do regime do xá e estabelecimento da República Islâmica sob o aiatolá Khomeini",
      "1970: Allende e o golpe no Chile - Salvador Allende se torna o primeiro presidente socialista eleito democraticamente na América Latina (1970), derrubado em 1973 🇨🇱",
      "1970-80: Movimento Sandinista na Nicarágua - Revolução contra a ditadura somozista 🇳🇮",
      "1990: O início da ALBA (Aliança Bolivariana para os Povos de Nossa América) - Iniciativa de integração política e econômica entre países da América Latina com foco em solidariedade e justiça social",
      "1991: Fim da União Soviética - Fim do governo comunista na URSS",
      "1991: Fim da Guerra Fria - Fim da União Soviética, desintegração do bloco socialista e reorganização do cenário internacional com os EUA como potência dominante",
      "1999: Hugo Chávez assume a presidência da Venezuela - Início do processo de reformas sociais e políticas bolivarianas 🇻🇪",
      "2001: Ataques de 11 de setembro - Transformação no cenário geopolítico global, com a invasão do Afeganistão.",
      "2003: Invasão do Iraque - Guerra liderada pelos EUA para derrubar Saddam Hussein, desencadeando um novo ciclo de instabilidade no Oriente Médio",
      "2005: A Cúpula das Américas - Discussão sobre a integração regional e o fortalecimento da democracia na América Latina",
      "2008: Crise financeira global - A crise afetou as economias internacionais, levando a novas políticas monetárias e econômicas globais, além de mudanças geopolíticas",
      "2010: Primavera Árabe - Série de protestos, revoluções e golpes de estado que derrubaram governos e geraram instabilidade no Oriente Médio e Norte da África",
      "2016: Brexit - O Reino Unido decide deixar a União Europeia, impactando a política e a economia internacional",
      "2017: Acordo de Paris sobre o clima - Acordo global para combater as mudanças climáticas, com compromisso de países para limitar o aquecimento global",
      "2020: Crise política nos EUA - Polarização política crescente, com a eleição de Donald Trump e a subsequente tentativa de golpe após sua derrota nas eleições de 2020",
      "2021: Ascensão da China - A China se torna uma superpotência global, desafiando o domínio dos EUA, com projetos como a Iniciativa do Cinturão e Rota"
    ],

    globalizacao: [
      "1995: Criação da OMC - Organização Mundial do Comércio, com o objetivo de liberalizar o comércio internacional e promover o desenvolvimento econômico global",
      "1994: NAFTA - Acordo entre EUA, Canadá e México que elimina barreiras comerciais e integra economias da América do Norte",
      "2000s: Globalização digital - A revolução da internet e da tecnologia transforma o comércio e as relações internacionais, conectando economias e sociedades de maneira inédita",
      "2008: Crise financeira global - A crise subprime nos EUA afeta todos os mercados financeiros globais, aprofundando a interdependência das economias",
      "2016: Brexit - O Reino Unido decide sair da União Europeia, gerando debates sobre os impactos da globalização e das barreiras econômicas e políticas na Europa",
      "2020: Pandemia de COVID-19 - Interrupção das cadeias globais de suprimentos, afetando diretamente o comércio e a circulação internacional de bens e pessoas",
      "2020s: Desglobalização - Movimento crescente contra a globalização, com políticas protecionistas e nacionalistas ganhando força em várias partes do mundo",
      "2021: Aumento do comércio eletrônico - A pandemia acelerou o crescimento do comércio eletrônico, mudando permanentemente os modelos de negócios e a logística internacional",
      "2023: Crise de fornecimento de chips - A escassez de semicondutores, agravada pela pandemia e pela guerra, impacta indústrias globais de tecnologia e automóveis"
    ],

    historia_politica_brasileira: [
      "1889: Proclamação da República - Fim do Império e início da República no Brasil 🇧🇷",
      "1922: Fundação do Partido Comunista Brasileiro (PCB) - Influência do movimento bolchevique e crescimento do comunismo no Brasil 🇧🇷",
      "1930: Revolução de 1930 - Getúlio Vargas assume o poder após golpe militar",
      "1935: Intentona Comunista - Luís Carlos Prestes, líder do PCB, lidera um levante contra o governo Vargas, que é fracassado e resulta em sua prisão 🇧🇷",
      "1937-1945: Estado Novo - Regime autoritário sob Getúlio Vargas 🇧🇷",
      "1943: PCB e a luta contra o Estado Novo - Participação do Partido Comunista Brasileiro na resistência contra o regime de Getúlio Vargas 🇧🇷",
      "1945: Getúlio Vargas e o PCB - O Partido Comunista Brasileiro ganha força política durante o governo Vargas, mas enfrenta repressão após o fim da Segunda Guerra Mundial 🇧🇷",
      "1945: Fim do Estado Novo e ascensão do PCB no Brasil - O PCB se torna um dos maiores partidos políticos brasileiros após a queda do regime de Vargas 🇧🇷",
      "1964: Golpe militar e instauração da ditadura militar (1964-1985) - Restrição de liberdades políticas e repressão",
      "1985: Fim da ditadura militar e transição para a democracia com a eleição de Tancredo Neves 🇧🇷",
      "2002: Eleição de Luiz Inácio Lula da Silva - Início do governo petista, focado na redução da desigualdade social 🇧🇷",
      "2016: Impeachment de Dilma Rousseff - Processo de impeachment controverso que levou à destituição da presidente Dilma Rousseff 🇧🇷",
      "2018: Eleição de Jair Bolsonaro - Adoção de uma agenda conservadora e de mudanças na política externa brasileira 🇧🇷",
      "2022: Eleição de Luiz Inácio Lula da Silva - Retorno ao poder após a vitória nas eleições presidenciais 🇧🇷"
    ],
    historia_politica_chinesa: [
      "1911: Revolução Xinhai - Fim da dinastia Qing e início da República da China 🇨🇳",
      "1921: Fundação do Partido Comunista Chinês - Início do movimento comunista na China 🇨🇳",
      "1949: Revolução Comunista - Mao Zedong funda a República Popular da China 🇨🇳",
      "1958-1962: Grande Salto Adiante - Tentativa de acelerar a industrialização da China, resultando em uma grande fome 🇨🇳",
      "1966-1976: Revolução Cultural - Movimento liderado por Mao Zedong para preservar o comunismo, resultando em perseguições e caos social 🇨🇳",
      "1968: Fundação do MR-8 (Movimento Revolucionário 8 de Outubro) - Organização guerrilheira de esquerda que se opôs à ditadura militar e foi influenciada pela Revolução Cubana 🇧🇷",
      "1968-1973: Guerrilha do Araguaia - Movimento guerrilheiro no interior do Brasil com participação do PCB e de outros grupos de esquerda, que foi duramente reprimido pelo regime militar 🇧🇷",
      "1969: Fundação da ALN (Ação Libertadora Nacional) - Movimento guerrilheiro que combateu a ditadura militar no Brasil, com destaque para Carlos Marighella 🇧🇷",
      "1969: Assassínio de Carlos Marighella - Marighella é morto pela ditadura militar em um confronto com as forças de segurança 🇧🇷",
      "1970-80: Vanguarda Revolucionária - Grupo guerrilheiro que se destacou na luta armada contra a ditadura militar no Brasil, com vínculos com o PCB 🇧🇷",
      "1971: Assassínio de Carlos Lamarca - Ex-membro do PCB e líder da resistência contra a ditadura militar, morto em combate 🇧🇷",
      "1978: Reforma e Abertura - Deng Xiaoping inicia reformas econômicas, afastando-se das políticas radicais de Mao 🇨🇳",
      "1980: Formação do Partido Comunista Brasileiro (PCB) após a ditadura militar - O PCB se reorganiza após os anos de repressão da ditadura e continua sua luta política no Brasil 🇧🇷",      
      "1980: Criação do Partido dos Trabalhadores (PT) - Fundado por líderes do movimento sindical e ex-membros do PCB, como Luiz Inácio Lula da Silva 🇧🇷",
      "1997: Retorno de Hong Kong à China - Fim da colonização britânica e retorno ao governo chinês 🇭🇰",
      "2000s: Ascensão econômica da China - A China se torna uma das principais economias do mundo, com uma estratégia de crescimento centrada no comércio internacional",
      "2013: Início da Iniciativa do Cinturão e Rota - Projeto de infraestrutura para conectar a Ásia à Europa e outras partes do mundo",
      "2018: Conflitos comerciais com os Estados Unidos - Guerra comercial com tarifas e políticas protecionistas impostas por ambos os países"
    ],

    Personalidades_ilustres: [
      "Luís Carlos Prestes - Líder comunista brasileiro, comandante da Coluna Prestes e um dos principais militantes de esquerda no Brasil 🇧🇷",
      "José Carlos Mariátegui - Intelectual peruano que foi um dos mais importantes marxistas latino-americanos, influenciando movimentos na América Latina 🇵🇪",
      "Fidel Castro - Líder da Revolução Cubana que desafiou o imperialismo dos EUA e estabeleceu um regime socialista na Cuba 🇨🇺",
      "Dilma Rousseff - Ex-presidenta do Brasil, militante marxista e guerrilheira que participou ativamente da luta contra a ditadura militar 🇧🇷",
      "Luiz Carlos Prestes - Líder comunista brasileiro e uma das maiores figuras militares da luta contra o regime militar 🇧🇷",
      "Leonel Brizola - Político brasileiro com forte vínculo com as causas trabalhistas e socialista, lutando contra as injustiças sociais no Brasil 🇧🇷",
      "Zumbi dos Palmares - Líder quilombola e símbolo da resistência negra e escrava no Brasil, combatendo a opressão colonial e escravagista 🇧🇷",
      "Salvador Allende - Primeiro presidente socialista eleito no Chile, cuja morte durante o golpe militar em 1973 marcou um período de grande repressão na América Latina 🇨🇱",
      "Augusto Sandino - Líder nicaraguense que lutou contra a ocupação dos EUA e se tornou um símbolo de resistência antiimperialista na América Latina 🇳🇮",
      "Hugo Chávez - Presidente venezuelano que promoveu o socialismo do século XXI e desafiou os EUA em diversas frentes políticas e econômicas 🇻🇪",
      "Evo Morales - Primeiro presidente indígena da Bolívia, conhecido por suas políticas de nacionalização e luta contra o imperialismo europeu e norte-americano 🇧🇴",
      "Víctor Jara - Cantor e ativista chileno que foi morto durante o golpe de Pinochet, símbolo da luta contra a ditadura e pela justiça social 🇨🇱",
      "Juan Domingo Perón - Presidente da Argentina e líder do movimento peronista, que misturava justiça social, nacionalismo e trabalhismo 🇦🇷",
      "Vladimir Lenin - Líder da Revolução Russa e fundador da União Soviética, criador do regime socialista soviético e defensor da luta proletária mundial 🇷🇺",
      "Mao Zedong - Líder da Revolução Chinesa e fundador da República Popular da China, implementando políticas de coletivização e a Revolução Cultural 🇨🇳",
      "Nelson Mandela - Líder sul-africano que lutou contra o apartheid e se tornou o primeiro presidente negro da África do Sul, promovendo a reconciliação nacional 🇿🇦",
      "Malcolm X - Ativista e líder afro-americano que lutou pela igualdade racial nos EUA, defendendo a autodeterminação dos negros e sendo um ícone da resistência 🇺🇸",
      "Sun Yat-sen - Revolucionário chinês que derrubou a dinastia Qing e fundou a República da China, sendo um dos primeiros defensores da democracia moderna na China 🇨🇳",
      "Martin Luther King Jr. - Líder dos direitos civis nos EUA, que usou a desobediência civil não violenta para combater a segregação racial e lutar pela igualdade 🕊️🇺🇸",
      "Ernesto 'Che' Guevara - Líder argentino que participou de revoluções em Cuba, Bolívia e outros países da América Latina, tornando-se um ícone revolucionário mundial 🇦🇷",
      "Leon Trotsky - Revolucionário russo que foi uma figura-chave na Revolução Russa, e mais tarde confrontou Stalin no Partido Comunista da União Soviética 🇷🇺",
      "Khomeini - Líder da Revolução Islâmica no Irã em 1979, que derrubou o regime do Xá e estabeleceu uma república islâmica com forte influência política e religiosa 🇮🇷",
      "Karl Marx - Filósofo e economista alemão, autor de 'O Capital', e coautor de 'O Manifesto Comunista', cujas ideias sobre o socialismo e a luta de classes influenciaram muitos movimentos revolucionários em todo o mundo 🇩🇪",
      "Rosa Luxemburgo - Revolucionária marxista e teórica que se destacou no movimento socialista e nas lutas pela revolução na Alemanha 🇩🇪",
      "Winston Churchill - Primeiro-ministro britânico durante a Segunda Guerra Mundial, conhecido por sua liderança contra a Alemanha nazista e por seu papel crucial na formação do bloco ocidental pós-guerra 🇬🇧",
      "Vladimir Lenin - Líder da Revolução Russa de 1917, fundador da União Soviética e figura central no desenvolvimento do marxismo-leninismo como ideologia política 🇷🇺",
      "Mahatma Gandhi - Líder indiano que usou a não-violência como meio de luta contra o domínio colonial britânico, sendo um ícone global da resistência pacífica 🇮🇳",
      "Desmond Tutu - Arcebispo e ativista sul-africano, líder no movimento contra o apartheid e defensor dos direitos humanos e da justiça social 🇿🇦",
      "Giuseppe Garibaldi - Líder militar italiano que desempenhou um papel crucial na unificação da Itália no século XIX, tornando-se um herói nacional 🇮🇹",
      "Charles de Gaulle - Líder militar e político francês, principal figura na resistência francesa durante a Segunda Guerra Mundial e fundador da Quinta República Francesa 🇫🇷",
      "Joseph Stalin - Líder soviético que sucedeu Lenin e consolidou o poder na União Soviética com políticas autoritárias e de industrialização forçada, mas também foi responsável pela vitória sobre os nazistas na Segunda Guerra Mundial 🇷🇺",
      "Carlos Marighella - Liderança revolucionária e um dos maiores guerrilheiros de esquerda no Brasil, focado no combate à ditadura militar 🇧🇷",
      "João Goulart - Presidente do Brasil deposto pelo golpe militar de 1964, defensor de reformas sociais e agrárias, e figura-chave do Brasil em período conturbado 🇧🇷",
      "Gamal Abdel Nasser - Líder egípcio que nacionalizou o Canal de Suez, enfrentou o imperialismo ocidental e promoveu um regime pan-árabe socialista 🇪🇬",
      "Getúlio Vargas - Presidente do Brasil que implementou o Estado Novo, uma ditadura corporativista, e depois retornou como presidente eleito, sendo fundamental para o desenvolvimento industrial do Brasil 🇧🇷",
      "Simón Bolívar - Líder militar e político venezuelano que foi uma figura central nas independências da América Latina, conhecido como 'El Libertador' 🇨🇴",
      "Emiliano Zapata - Líder revolucionário mexicano e ícone da luta camponesa durante a Revolução Mexicana, defendendo a reforma agrária 🇲🇽",
      "Che Guevara - Embora argentino, Che teve grande influência no Brasil e na América Latina, sendo um símbolo de resistência contra o imperialismo e defensor da revolução socialista 🇦🇷🇧🇷",

    ],
  }
};
